[package]
name = "cervisia-server"
version = "0.1.0"
authors = ["nephtys <christopher.kaag@gmail.com>"]

[dependencies]
iron = "*"
rustix-bl = "*"
time = "*"
staticfile = "*"
simple_logger = "*"
mount = "*"
log = "*"
lettre = "*"
notify = "*"
config = "*"
toml = "*"
serde = "*"
serde_derive = "*"